#!/usr/bin/env python3
"""Generate an SGE array-job script from a subject list.

    python cluster/make_array_job.py subjects.tsv jobs/run.arr

`subjects.tsv` is whitespace-separated, one subject per line:

    <subject>  <t1_image_id>  <flair_image_id>  [scan]

The generated script dispatches on $SGE_TASK_ID, so task N runs line N.
Submit it with cluster/submit_array.sh.

Original: QsubArray.py -- which hard-coded the row count, the working directory
and the output filename.
"""

from __future__ import annotations

import argparse
import os
import stat
from pathlib import Path

TEMPLATE_HEAD = """#!/bin/bash
# Generated by cluster/make_array_job.py -- do not edit by hand.
set -euo pipefail
echo "Beginning task $SGE_TASK_ID..."
cd {repo_root}
source config/config.sh

case "$SGE_TASK_ID" in
"""

TEMPLATE_TAIL = """*)
  echo "no such task: $SGE_TASK_ID" >&2
  exit 1
  ;;
esac
echo "Finished task $SGE_TASK_ID."
exit 0
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("subject_list", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--repo-root",
        default=os.environ.get("WMBA_ROOT", str(Path(__file__).resolve().parents[1])),
    )
    args = parser.parse_args()

    rows = []
    for lineno, line in enumerate(args.subject_list.read_text().splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split()
        if len(fields) < 3:
            raise SystemExit(
                f"{args.subject_list}:{lineno}: expected at least 3 fields, got {len(fields)}"
            )
        rows.append(fields)

    if not rows:
        raise SystemExit(f"no subjects in {args.subject_list}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="\n") as f:
        f.write(TEMPLATE_HEAD.format(repo_root=args.repo_root))
        # SGE task ids are 1-based.
        for task_id, fields in enumerate(rows, 1):
            subject, t1_id, flair_id = fields[0], fields[1], fields[2]
            scan = fields[3] if len(fields) > 3 else "0"
            f.write(f"{task_id})  # {task_id}/{len(rows)}\n")
            f.write(
                f'  bash bin/run_subject.sh "{subject}" '
                f'"$WMBA_T1_DIR/{t1_id}.nii.gz" "{flair_id}" "{scan}"\n'
            )
            f.write("  ;;\n")
        f.write(TEMPLATE_TAIL)

    args.output.chmod(args.output.stat().st_mode | stat.S_IEXEC)
    print(f"wrote {args.output} ({len(rows)} tasks)")
    print(f"submit with: cluster/submit_array.sh {args.output} {len(rows)}")


if __name__ == "__main__":
    main()
